version: "3.9"
services:
  delivery:
    container_name: delivery
    build: ./Delivery
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/delivery_db?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    image: oussamakaddech/deliveryms
    restart: unless-stopped
    depends_on:
      - eureka
      - db-mysql
    networks:
      - app-network

  eureka:
    container_name: eureka
    build: ./Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: oussamakaddech/eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=serviceregistry
    restart: unless-stopped
    networks:
      - app-network

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=delivery_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    build: ./Api_gateway
    image: oussamakaddech/apigateway
    ports:
      - "8093:8093"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka
      - delivery
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: