version: "3.9"
services:
  
    
  Candidat:
    container_name: candidat
    image: oussamakaddech/candidat
    build: .\Candidat
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/ 
    depends_on:
       - Eureka

 
 
  Job:
    container_name: job
    build: .\MS_Job_Board
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/jobTest?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/     
      
    image: oussamakaddech/jobms
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql
    
 
  Eureka:
    container_name: eureka
    build: .\Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"   
    image: oussamakaddech/eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    
  
  db-mysql:
      image: "mysql:5.6"
      container_name: db-mysql 
      environment:
        - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
        #- MYSQL_DATABASE=job
      ports:
        - "3306:3306"
      restart: unless-stopped
      
      
  api-gateway:
    build: .\Api_gateway
    image: oussamakaddech/apigateway
    ports:
      - "8093:8093"  # Port mapping pour l'API Gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - "Eureka"
      - "Candidat"
      - "Job"
      
  
  
  
    




  
  