version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: techgear-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techgear_users
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - techgear-network
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - techgear-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
    command: start-dev --import-realm
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - techgear-network
    restart: unless-stopped

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - techgear-network
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/techgear_users?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/techgear
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/techgear/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - keycloak
    networks:
      - techgear-network
    restart: on-failure:10

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/techgear
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/techgear/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/techgear
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: techgear-client
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: SjsmyTNP8TX3QkYNf3woG2GtxaCCUWDe
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: password
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: openid,profile
    ports:
      - "8093:8093"
    depends_on:
      - eureka-server
      - user-service
      - keycloak
    networks:
      - techgear-network
    restart: on-failure:10

  product-mysql:
    image: mysql:8.0
    container_name: techgear-product-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techgear_products
    ports:
      - "3307:3306"
    volumes:
      - product_mysql_data:/var/lib/mysql
    networks:
      - techgear-network
    restart: unless-stopped

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product-mysql:3306/techgear_products?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/techgear
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/techgear/protocol/openid-connect/certs
    ports:
      - "8083:8083"
    depends_on:
      - product-mysql
      - eureka-server
      - keycloak
    networks:
      - techgear-network
    restart: on-failure:10

volumes:
  mysql_data:
  postgres_data:
  product_mysql_data:

networks:
  techgear-network:
    driver: bridge