spring.application.name=User
server.port=8081

#Error1
spring.cloud.config.enabled=false

#Error3(eureka temporary fix)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT Configuration
jwt.secret=Th3Sm4llAuss1eKangarooJumps@roundEsprit!2025$SecureEnoughForNow#
jwt.expiration=86400000
jwt.refreshExpiration=604800000

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
spring.security.user.name=admin
spring.security.user.password=adminpass